version: '3.7'

services:
  books:
    build:
      dockerfile: Dockerfile
      context: .
    image: books
    volumes:
      - ./books:/app/books
      - ./wheelhouse:/app/wheelhouse
    env_file:
      - .env
    ports:
      - '5000:5000'
